export default Object.freeze({
    $bool: 'BOOLEAN',
    $varchar: "VARCHAR",
    $char: "CHAR",
    $text: "TEXT",
    $int: "INTEGER",
    $serial: "SERIAL",
    $si: "SMALLINT",
    $float:  'FLOAT',
    $real: 'REAL',
    $numeric: 'NUMERIC',
    $date: 'DATE',
    $time: 'TIME',
    $ts: 'TIMESTAMP',
    $tsz: 'TIMESTAMPZ',
    $interval: "INTERVAL",
    $json: 'JSON',
    $jsonb: 'JSONB',
    $uuid: 'UUID'
});
